### ISSUE TITLE
Improve 'Most Failed Packages' plot

### ISSUE THREAD

**Issue by rgaiacs** [prerit2010/Result-aggregation-server#19]
# Description

The bars are too much thin.
# Suggestion

Make the bars large and use two colors to make easy to know what package the bar correspond to.
# Screenshot

Before

![screencapture-localhost-5000-view-1468915093338](https://cloud.githubusercontent.com/assets/1506457/16942814/1e41f652-4d90-11e6-8ec5-edf2fc53204c.png)

After

![screencapture-localhost-5000-view-1468915093338-plot](https://cloud.githubusercontent.com/assets/1506457/16942823/26ad50e8-4d90-11e6-89a2-730206f06500.png)

**Comment by prerit2010** [comment]
@rgaiacs  Thiis is because the list of failed packages is huge, and thus it would require a lot of scrolling to view the whole chart. To avoid this it is showing some of the values only. To have a look at all the values, you can zoom in the chart by drawing a box like this : 
![image](http://imgur.com/drfLxyM.png)

**Comment by rgaiacs** [comment]
Can we limit this plot to the top 10? And add one link to the full plot where people need to scroll?

**Comment by prerit2010** [comment]
That will be good. I'll try that. :-)
