### ISSUE TITLE
Plot doesn't show the name of the first package

### ISSUE THREAD

**Issue by rgaiacs** [prerit2010/Result-aggregation-server#25]
# Screenshot

![screenshot_2016-07-24_15-04-28](https://cloud.githubusercontent.com/assets/1506457/17084202/0d59dd7c-51b0-11e6-819f-db901c7cee9f.png)
# How to reproduce

Move the mouse to the first bar.

![screenshot_2016-07-24_15-04-16](https://cloud.githubusercontent.com/assets/1506457/17084199/025cc1dc-51b0-11e6-85b6-7ac51278e136.png)

'Web browser' will pop up. But it isn't list on the y axis.

**Comment by prerit2010** [comment]
@rgaiacs plotly selects a few of the names to be displayed on its own. And apparently that package is the last one instead of the first (for this case), considering we are more bothered about the most failed packages, which start from the bottom in a sorted sequence.

**Comment by rgaiacs** [comment]
> plotly selects a few of the names to be displayed on its own.

I don't think this is suitable for us.

**Comment by prerit2010** [comment]
@rgaiacs As the failed package list is huge, it can't be possible to show all the names anyway. So, one work around can be to limit the number of packages for graph, so that plotly doesn't have to select on its own.
The whole idea behind the graph is to visualize it in one go. Having a huge graph with scrolling would make it nothing different from a table that we have shown below the graph. So I think limiting would be the best. May be can have options like :  top 10, top 20 failed packages to be visualized through graph.
What do you think ?

**Comment by rgaiacs** [comment]
> top 10
