### ISSUE TITLE
Ideas on Charts and statistics

### ISSUE THREAD

**Issue by prerit2010** [prerit2010/Result-aggregation-server#5]
Here we can have some ideas on charts and statistics that we can prepare from the data.

**Comment by pbanaszkiewicz** [comment]
Preview: http://installation.software-carpentry.org/view/

**Comment by pbanaszkiewicz** [comment]
Charts looking nice.

On the charts we may want numbers, not only percentages, though -- I'm not sure if plotly supports displaying both.

Idea for a chart: N most/least failing packages.

Idea: filtering of the "Most Failed Packages" because right now it's hard to see package names. Or using a horizontal view, not vertical.

**Comment by rgaiacs** [comment]
Can we filter the data based on workshop? For example, http://installation.software-carpentry.org/view/YYYY-MM-someplace?

**Comment by prerit2010** [comment]
Yes, that's already on my list, and I have been working on this only today. :-)

**Comment by rgaiacs** [comment]
Also, provide one way to export the raw information (maybe as JSON). Something like  http://installation.software-carpentry.org/view/?export=json or  http://installation.software-carpentry.org/raw/.

**Comment by prerit2010** [comment]
That'll be nice to have the raw json in place :+1:

**Comment by rgaiacs** [comment]
@prerit2010 Can we close this one?
